Supprime toutes les références aux annotations pour les la gestion des exceptions attendu
sebastianbergmann/phpunit-documentation-french pull request #76
Opened 2021-07-31 12:18 UTC by Fred-si

Références  supprimées dans la doc original par le commit https://github.com/sebastianbergmann/phpunit-documentation-english/commit/d2dec21cc019f9293ee6a3404d3a5420aa6a9bcf#diff-41d250ab08bcc36ddadc649bcf3d78e0607ba9d5997cfb003cab38d245fe7089

2021-08-07 11:45 UTC, dzc34 approved these changes

2021-08-07 11:48 UTC, dzc34 commented on src/writing-tests-for-phpunit.rst
> -.. _writing-tests-for-phpunit.errors:
cette ligne ne semble pas supprimé dans le commit suivant :

2021-08-07 11:53 UTC, dzc34 commented on src/writing-tests-for-phpunit.rst
> -        /**
7 lignes au dessus  `:caption: Attendre une erreur PHP en utilisant @expectedException`
doit peut-être être modifié comme ici : https://github.com/sebastianbergmann/phpunit-documentation-english/commit/d2dec21cc019f9293ee6a3404d3a5420aa6a9bcf#diff-41d250ab08bcc36ddadc649bcf3d78e0607ba9d5997cfb003cab38d245fe7089R673

2021-08-07 11:55 UTC, dzc34 requested changes
merci @Fred-si  pour ce correctif.

quelques lignes qu'il faut peut-être vérifier en commentaire.

2021-08-07 21:52 UTC, Fred-si commented on src/writing-tests-for-phpunit.rst
> -.. _writing-tests-for-phpunit.errors:
Je suis allé trop vite, cette ligne n’était effectivement pas à supprimer

2021-08-07 22:01 UTC, Fred-si commented on src/writing-tests-for-phpunit.rst
> -        /**
J’étais passé à coté. C’est corrigé

2021-08-07 22:07 UTC, Fred-si commented
Bonjour @dzc34

J’ai corrigé en tenant compte des remarques.

2021-08-08 10:18 UTC, dzc34 approved these changes

2021-08-08 10:18 UTC, merged

2021-08-08 10:21 UTC, dzc34 commented
Bonjour @Fred-si,

C'est mergé.
Encore merci pour le correctif.  :+1: